### ISSUE TITLE
Enhancement: don’t resize when dimension changes are small

### ISSUE THREAD

**Issue by eigengrau** [roman/golden-ratio.el#65]
Sometimes, screen dimensions and window configuration are such that the resizing done by golden-ratio results in a negligible change. It might be convenient to have a customizable variable containing a threshold value which allows avoiding the «jumpyness» of resizing the window dimensions when there is little to be gained in terms of window balance.

**Comment by shouya** [comment]
I use a `(setq golden-ratio--value 2)` config which corresponds to a 50:50 split for my windows. This package works great for my usual workflow of having two windows, and occasionally I have more than two windows and am glad to have the focused window larger.

However, when using a vertical layout, sometimes the two windows cannot be evenly split. In that case, jumping around could trigger in miniscule resizing, which is a visual burden because I have to follow the shifting of the content on the buffers. So I also prefer window not resizing if the adjustment needed is really small.
