### ISSUE TITLE
Is this package stop maintained?

### ISSUE THREAD

**Issue by tumashu** [roman/golden-ratio.el#78]

**Comment by roman** [comment]
Well, no... 

I use this library __everyday__, and on my current setup, it works perfectly. If for some reason is not working for you, I invite you to open a PR.

My goal is not to be spacemacs :-), I like to share the stuff I do to others, but sadly, I don't have the bandwidth to fix problems that others may have because of their particular setup.

At the moment there is an issue that clearly doesn't make the library work, I would be on top of that.

Cheers.

**Comment by humitos** [comment]
Hi! I also use this library in my day to day and it's working as I expect :)

BTW, thanks for doing it ;)

**Comment by azzamsa** [comment]
@roman Hi. Thank you for awesome package.

Could we please fix this problem. https://github.com/roman/golden-ratio.el/issues/72. It's already fixed from eyebrowse side https://github.com/wasamasa/eyebrowse/issues/56

Thank you in advance.

**Comment by roman** [comment]
@azzamsa I'll work in merging #66 and ensure that things keep working as expected. If so, I will merge that issue. If for some reason that doesn't solve the errors with eyebrowse, I'll kindly invite you to create a pull request with something that solves the issue and is backward compatible.

I'm likely not going to work in a solution, as at the current moment I'm not a user of the eyebrowse package.

Thanks for the feedback!

**Comment by stardiviner** [comment]
I will try to add an adivice to disable goden-ratio before eyebrowse switching for temporaly workaround for this issue.

**Comment by roman** [comment]
@azzamsa sorry for the long delay, #66 has been merged. I'm going to close this ticket now

**Comment by azzamsa** [comment]
:tada:  :)

Thank you for golden-ratio.
